import { CreateCompanyDTO, ProfileFormData } from "@/types/user";
import { requirementsByDepartment } from "@/utils/onboardingRequirements";

const firstDept = Object.keys(requirementsByDepartment)[0] || "";

export const blankProfileFormData: ProfileFormData = {
  _id: "",
  staffId: "",
  title: "",
  firstName: "",
  middleName: "",
  lastName: "",
  gender: "",
  dateOfBirth: "",
  stateOfOrigin: "",
  address: "",
  city: "",
  mobile: "",
  email: "",
  departments: [
    {
      name: "Select department",
      supervisor: "",
      sopDocument: "",
      company: "",
      _id: "none",
    },
  ],
  department: "none",
  biometryId: "",
  profileImage: "",
  position: "none",
  officeBranch: "",
  employmentDate: "",
  accountInfo: {
    classLevel: "",
    basicPay: 0,
    allowances: 0,
    bankAccountNumber: "",
    bankName: "",
    taxNumber: "",
    pensionCompany: "",
    pensionNumber: "",
  },
  role: "employee",
  company: {
    name: "",
    description: "",
    roles: "",
    department: "",
    status: "",
    branding: {
      displayName: "",
      logoUrl: "",
      primaryColor: "",
    },
  },
  status: "active",
  terminationDate: "",
  isActive: false,
  failedLoginAttempts: 0,
  lockUntil: "",
  resetRequested: false,
  resetRequestedAt: "",
  twoFactorEnabled: false,
  twoFactorCode: "",
  twoFactorExpiry: "",
  resetToken: "",
  resetTokenExpiry: "",
  cooperative: {
    monthlyContribution: 0,
    totalContributed: 0,
    lastContributionDate: "",
  },
  createdAt: "",
  nextOfKin: {
    name: "",
    phone: "",
    email: "",
    relationship: "",
  },
  sendInvite: false,
  departmentName: "",
  requirements: [],

  selectedDepartment: firstDept,
  classlevels: [],
};

export const blankCompanyFormData: CreateCompanyDTO = {
  companyName: "",
  companyDescription: "",
  adminData: {
    firstName: "",
    lastName: "",
    email: "",
    title: "Mr",
    gender: "male",
    staffId: "",
  },
  branding: {
    displayName: "",
    logoUrl: "",
    primaryColor: "#000000",
  },
};
